### ISSUE TITLE
RuntimeError: CuDNN error: CUDNN_STATUS_SUCCESS

### ISSUE THREAD

**Issue by Goru1890** [fperazzi/proSR#1]
I'm trying to test your project just for fun, every time I try to run it I get a runtime error. I'm not sure if it uses my GPU.

python test.py -i C:\Users\Usuario\Pictures\marcos\64039.jpg --checkpoint C:\Users\Usuario\Documents\IAPOR\proSRGAN\proSRGAN\proSRGAN_x4.pth --scale 4 -o C:\Users\Usuario\Pictures\marcos\new

←[0;97m2021-08-29 19:18:03: phase: phase.TEST←[0;97m←[0m
←[0;97m2021-08-29 19:18:03: checkpoint: proSRGAN_x4.pth←[0;97m←[0m
{'D': {'act_params': {'negative_slope': 0.2},
       'act_type': 'LRELU',
       'input_residual': True,
       'ndf': 64,
       'scale_overhead': True,
       'update_freq': 2,
       'use_lsgan': True,
       'warmup_epochs': 0,
       'which_epoch': 'latest',
       'which_model_netD': 'srgan'},
 'G': {'bn_size': 4,
       'growth_rate': 40,
       'level_compression': -1,
       'level_config': [[8, 8, 8, 8, 8, 8, 8, 8, 8], [8, 8, 8], [8]],
       'max_num_feature': 312,
       'max_scale': 8,
       'num_init_features': 160,
       'ps_woReLU': False,
       'res_factor': 0.2,
       'residual_denseblock': True,
       'vgg': [2, 4],
       'vgg_mean_pool': True},
 'data': {'input_size': [48, 36, 24], 'scale': [2, 4, 8]},
 'test': {'dataset': {'downscale': False,
                      'path': {'source': '', 'target': 'data/datasets/Set14'},
                      'stddev': [0.0039215, 0.0039215, 0.0039215]},
          'fast_validation': -1},
 'train': {'D_lr': 0.0001,
           'batch_size': 16,
           'dataset': {'downscale': False,
                       'mean': [0.4488, 0.4371, 0.404],
                       'path': {'source': '',
                                'target': 'data/datasets/DIV2K/DIV2K_train_HR'},
                       'stddev': [0.0039215, 0.0039215, 0.0039215]},
           'epochs': 500,
           'gan_loss_weight': 1,
           'growing_steps': [0.12, 0.25, 0.45, 0.6, 1.0],
           'io': {'eval_epoch_freq': 10,
                  'print_errors_freq': 100,
                  'save_model_freq': 20},
           'l1_loss_weight': 0,
           'lr': 0.0001,
           'lr_decay': 0.5,
           'lr_schedule_patience': 30,
           'smallest_lr': 1e-05,
           'vgg_loss_weight': [0.5, 2]}}
←[0;97m2021-08-29 19:24:35: Saving images in: C:\Users\Usuario\Pictures\marcos\new←[0;97m←[0m
Traceback (most recent call last):
  File "test.py", line 156, in <module>
    output = model(input,args.scale).cpu() + data['bicubic']
  File "C:\Users\Usuario\anaconda3\envs\proSR\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Usuario\Documents\IAPOR\proSR\lib\prosr\models\generators.py", line 121, in forward
    feats = self.get_init_conv(log2(upscale_factor))(x)
  File "C:\Users\Usuario\anaconda3\envs\proSR\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Usuario\Documents\IAPOR\proSR\lib\prosr\models\layers.py", line 64, in forward
    return self.conv(x)
  File "C:\Users\Usuario\anaconda3\envs\proSR\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Usuario\anaconda3\envs\proSR\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "C:\Users\Usuario\anaconda3\envs\proSR\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Usuario\anaconda3\envs\proSR\lib\site-packages\torch\nn\modules\conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CuDNN error: CUDNN_STATUS_SUCCESS

**Comment by SamHSlva** [comment]
Were you able to fix it?

**Comment by ayub567** [comment]
Hello dear 

i am facing this issue

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from prosr import Phase
  File "/content/proSR/prosr/__init__.py", line 2, in <module>
    from . import metrics
  File "/content/proSR/prosr/metrics.py", line 4, in <module>
    from skimage.measure import compare_psnr, compare_ssim
ImportError: cannot import name 'compare_psnr' from 'skimage.measure' (/usr/local/lib/python3.8/dist-packages/skimage/measure/__init__.py)

please replay
