### ISSUE TITLE
Is it possible to run inference without CUDA?

### ISSUE THREAD

**Issue by noobmaster29** [fperazzi/proSR#10]
I'm not attempting to train the model without a GPU but just want to try test.py. I have replaced checkpoint = torch.load(args.checkpoint) with 
    checkpoint = torch.load(args.checkpoint, map_location='cpu'). However, I still get this error message: Traceback (most recent call last):
  File "test.py", line 114, in <module>
    output = model(data['input'].cuda(),
RuntimeError: Cannot initialize CUDA without ATen_cuda library. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using ldd on your binary to see if there is a dependency on *_cuda.so library.

Just working if it is possible to run this without a CUDA GPU. :)

**Comment by DatoJanez** [comment]
in pytorch you can use GPU by adding cuda() method to variable, you can just remove cuda() and modify it like this 
`output = model(data['input'], args.scale).cpu() + data['bicubic']`

**Comment by fperazzi** [comment]
I added to `test.py` a command line option `--cpu` that disable CUDA. Let me know if that works for you.

**Comment by scotshinderman** [comment]
I also tried this:
python test.py --cpu  --checkpoint data/checkpoints/proSR.pth  --scale 3  -i ~/Desktop/UprezCompare1/Media/Shot1.png  -t Uprez1.png  -o /tmp
but get the following:

> RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.


changing the load line:
checkpoint = torch.load(args.checkpoint, map_location=lambda storage, location: 'cpu')
it gets a little further along -- I'll try debugging that today ;)

Traceback (most recent call last):
 

 

> File "test.py", line 75, in <module>
>     checkpoint = torch.load(args.checkpoint, map_location=lambda storage, location: 'cpu')
>   File "/Users/scot/third/my-venv/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
>     return _load(f, map_location, pickle_module)
>   File "/Users/scot/third/my-venv/lib/python3.6/site-packages/torch/serialization.py", line 542, in _load
>     result = unpickler.load()
>   File "/Users/scot/third/my-venv/lib/python3.6/site-packages/torch/_utils.py", line 98, in _rebuild_tensor_v2
>     tensor = _rebuild_tensor(storage, storage_offset, size, stride)
>   File "/Users/scot/third/my-venv/lib/python3.6/site-packages/torch/_utils.py", line 92, in _rebuild_tensor
>     module = importlib.import_module(storage.__module__)
> AttributeError: 'str' object has no attribute '__module__'
>

**Comment by fperazzi** [comment]
Thanks for posting the fix!
