### ISSUE TITLE
Upgrading to GeForce RTX broke proSR

### ISSUE THREAD

**Issue by Shadetail** [fperazzi/proSR#22]
ProSR worked perfectly until the exact moment I upgraded from GTX 1080 to RTX 2080Ti.

Now I'm getting: RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

I suspect that this is caused by newer than supported version of CUDA and/or cuDNN. I guess that this got updated automatically when hardware was upgraded.

I first tried updating both CUDA and cuDNN to latest versions CUDA 10, cuDNN v7.3.0 for CUDA 10.0), but it didn't help, after which I tried CUDA 9.2 and cuDNN v7.2.1 for CUDA 9.2, same thing. And when I tried to go further down to CUDA 9.1 (which I understand proSR is developed on), I first got a [warning about hardware incompatibility](https://i.imgur.com/GasNqjO.png), after which I tried to install all but driver, but the install failed anyways (after requested reboot, CUDA was nowhere to be found). So it turns out CUDA 9.1 is not compatible with RTX GPU.

So I'm guessing this could be due to CUDA, but is it really? And is there anything I could do to make it work?

Here is the full output:

```
[0;97m2018-10-02 22:48:32: phase: phase.TEST[0;97m[0m
[0;97m2018-10-02 22:48:32: checkpoint: proSRGAN_x4.pth[0;97m[0m
{'D': {'act_params': {'negative_slope': 0.2},
       'act_type': 'LRELU',
       'input_residual': True,
       'ndf': 64,
       'scale_overhead': True,
       'update_freq': 2,
       'use_lsgan': True,
       'warmup_epochs': 0,
       'which_epoch': 'latest',
       'which_model_netD': 'srgan'},
 'G': {'bn_size': 4,
       'growth_rate': 40,
       'level_compression': -1,
       'level_config': [[8, 8, 8, 8, 8, 8, 8, 8, 8], [8, 8, 8], [8]],
       'max_num_feature': 312,
       'max_scale': 8,
       'num_init_features': 160,
       'ps_woReLU': False,
       'res_factor': 0.2,
       'residual_denseblock': True,
       'vgg': [2, 4],
       'vgg_mean_pool': True},
 'data': {'input_size': [48, 36, 24], 'scale': [2, 4, 8]},
 'test': {'dataset': {'downscale': False,
                      'path': {'source': '', 'target': 'data/datasets/Set14'},
                      'stddev': [0.0039215, 0.0039215, 0.0039215]},
          'fast_validation': -1},
 'train': {'D_lr': 0.0001,
           'batch_size': 16,
           'dataset': {'downscale': False,
                       'mean': [0.4488, 0.4371, 0.404],
                       'path': {'source': '',
                                'target': 'data/datasets/DIV2K/DIV2K_train_HR'},
                       'stddev': [0.0039215, 0.0039215, 0.0039215]},
           'epochs': 500,
           'gan_loss_weight': 1,
           'growing_steps': [0.12, 0.25, 0.45, 0.6, 1.0],
           'io': {'eval_epoch_freq': 10,
                  'print_errors_freq': 100,
                  'save_model_freq': 20},
           'l1_loss_weight': 0,
           'lr': 0.0001,
           'lr_decay': 0.5,
           'lr_schedule_patience': 30,
           'smallest_lr': 1e-05,
           'vgg_loss_weight': [0.5, 2]}}
[0;97m2018-10-02 22:48:36: Saving images in: output[0;97m[0m
Traceback (most recent call last):
  File "test.py", line 123, in <module>
    output = model(input, args.scale).cpu() + data['bicubic']
  File "C:\Users\mario\Anaconda3\envs\proSR\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\mario\Anaconda3\envs\proSR\lib\prosr\models\generators.py", line 121, in forward
    feats = self.get_init_conv(log2(upscale_factor))(x)
  File "C:\Users\mario\Anaconda3\envs\proSR\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\mario\Anaconda3\envs\proSR\lib\prosr\models\layers.py", line 64, in forward
    return self.conv(x)
  File "C:\Users\mario\Anaconda3\envs\proSR\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\mario\Anaconda3\envs\proSR\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "C:\Users\mario\Anaconda3\envs\proSR\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\mario\Anaconda3\envs\proSR\lib\site-packages\torch\nn\modules\conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED
```

**Comment by fperazzi** [comment]
Did you create a new conda environment after the update?

**Comment by Shadetail** [comment]
I just tried to setup a new environment (I called it prosr2, hopefully name doesn't matter), and the exact same error is happening. Do you have any other ideas about what to do (short of downgrading back to GTX1080)?

**Comment by mexicantexan** [comment]
@fperazzi Is there any plans to upgrade this to Pytorch 1.0 with CUDA 10.0 support?

**Comment by fperazzi** [comment]
Not at the moment. But happy to merge a pull request if someone does so.

Best,
Federico
