### ISSUE TITLE
Trouble to get it works (No module named 'prosr')

### ISSUE THREAD

**Issue by satsukiyatoshi** [fperazzi/proSR#42]
Hello.
I'm using windows 10
I've installed anaconda and all dependencys as specified.
But when i try to use the test.py i got "No module named 'prosr'"

Thanks a lot

**Comment by thomasmomme** [comment]
You need to add the 'prosr' (located in 'lib') folder to the python path, as is specified in the readme file. There are several ways this can be done. Alternatively you can move the 'prosr' folder to the root of the project folder 'proSR'. Then your interpreter should be able to find it without any other changes.

**Comment by satsukiyatoshi** [comment]
Thanks for answering.
If i copy the prosr folder to the root with the test.py file a got this error : "ImportError: cannot import name 'Phase'"

**Comment by fperazzi** [comment]
Include the path to prosr/lib in the PYTHONPATH as described in the README.

**Comment by satsukiyatoshi** [comment]
tried that too.
I've done a full reinstall with miniconda (tried anaconda too).
If i don't had to the path i get "No module named 'prosr'"
If i add to the path i get "ImportError: cannot import name 'Phase'"

thanks

**Comment by kai-pinckard** [comment]
I also encountered this error. I was able to fix it by running the command:
export PYTHONPATH=/home/kai/investigate/proSR/lib:$PYTHONPATH

However, I then encountered a second error. 
  File "test.py", line 3, in <module>
    from prosr import Phase
  File "/home/kai/investigate/proSR/lib/prosr/__init__.py", line 4, in <module>
    from .config import prosrs_params, prosr_params, prosrgan_params, debug_params
  File "/home/kai/investigate/proSR/lib/prosr/config.py", line 3, in <module>
    from easydict import EasyDict as edict
ModuleNotFoundError: No module named 'easydict'

I have installed easy dict with pip but I am inside my conda env (I have activated my env). How can I fix this? Is your code running inside of two different python environments (the standard environment and the conda environment created for this project)?

**Comment by kai-pinckard** [comment]
I was able to resolve the easyDict error by running the command:
conda install -c conda-forge easydict

**Comment by rajdeepdebnath** [comment]
can you generate HR image from LR input image?

**Comment by Hager-ahmed2021** [comment]
(proSR3) C:\Users\User\anaconda3\envs\proSR3\proSR-master\proSR-master>python test.py -i inputs  --checkpoint models/proSR_x2.pth --scale 4 -o outputs
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from prosr import Phase
ModuleNotFoundError: No module named 'prosr'
THAT MY ERROR IN WINDOWS 10
