### ISSUE TITLE
training doesn't work

### ISSUE THREAD

**Issue by ManoaNosea** [fperazzi/proSR#50]
```
python train.py --config options\prosr.yaml --output data\checkpoints\dod
train.py:293: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  params = edict(yaml.load(stream))
{'G': {'bn_size': 4,
       'growth_rate': 40,
       'level_compression': -1,
       'level_config': [[8, 8, 8, 8, 8, 8, 8, 8, 8], [8, 8, 8], [8]],
       'max_num_feature': 312,
       'num_init_features': 160,
       'ps_woReLU': False,
       'res_factor': 0.2,
       'residual_denseblock': True},
 'cmd': {'checkpoint': None,
         'config': 'options\\prosr.yaml',
         'model': None,
         'no_curriculum': False,
         'output': 'data\\checkpoints\\dod',
         'seed': 128,
         'visdom': False,
         'visdom_port': 8067},
 'data': {'input_size': [48, 36, 24], 'scale': [2, 4, 8]},
 'test': {'dataset': {'downscale': False,
                      'mean': [0.4488, 0.4371, 0.404],
                      'path': {'source': '', 'target': 'data/dod/HR'},
                      'stddev': [0.0039215, 0.0039215, 0.0039215]},
          'fast_validation': -1},
 'train': {'batch_size': 16,
           'dataset': {'downscale': False,
                       'mean': [0.4488, 0.4371, 0.404],
                       'path': {'source': '', 'target': 'data/dod/HR'},
                       'stddev': [0.0039215, 0.0039215, 0.0039215]},
           'epochs': 300,
           'growing_steps': [0.12, 0.25, 0.45, 0.6, 1.0],
           'io': {'eval_epoch_freq': 10,
                  'print_errors_freq': 100,
                  'save_model_freq': 10},
           'l1_loss_weight': 1.0,
           'lr': 0.0001,
           'lr_decay': 0.5,
           'lr_schedule_patience': 30,
           'smallest_lr': 1e-05}}
2019-12-18 14:58:12: experiment ID: dod
2019-12-18 14:58:13: training images = 1272
2019-12-18 14:58:13: validation images = 1272
2019-12-18 14:58:16: start training with scales: [2]
2019-12-18 14:58:16: start training from epoch 0, learning rate 1.000000e-04
Traceback (most recent call last):
  File "train.py", line 325, in <module>
    main(params)
  File "train.py", line 177, in main
    for i, data in enumerate(trainer.training_dataset):
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\proSR-torch1\prosr\data\multiproc.py", line 152, in __next__
    return self._process_next_batch(batch)
  File "E:\programs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\proSR-torch1\prosr\data\multiproc.py", line 50, in _worker_loop
    samples = collate_fn([dataset.get(i, random_var) for i in batch_indices])
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\proSR-torch1\prosr\data\multiproc.py", line 50, in <listcomp>
    samples = collate_fn([dataset.get(i, random_var) for i in batch_indices])
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\proSR-torch1\prosr\data\progressive_loader.py", line 106, in get
    ret_data['input'])
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\proSR-torch1\prosr\data\util.py", line 60, in random_crop_pairs
    offx_lr = random.randint(x0, x1)
  File "mtrand.pyx", line 992, in mtrand.RandomState.randint
ValueError: Range cannot be empty (low >= high) unless no samples are taken
```

**Comment by fperazzi** [comment]
x0 > x1 in random.randint(x0, x1),  not sure why, maybe samples not loaded correctly?

**Comment by ManoaNosea** [comment]
no change, he says the same thing :x

**Comment by ManoaNosea** [comment]
this is because some images too small, what is the image minimum size limit ?

**Comment by ManoaNosea** [comment]
looks like it's 96 in any dimension in prosrgan options file

**Comment by ManoaNosea** [comment]
is minimum size of any dimension of image is data.input_size * data.scale ?
