### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by johannhost** [fperazzi/proSR#70]
I was following a tutorial but its not working. Im new to anaconda and github, can someone tell me what I need to to in order to fix the code?

(D:\proSR) D:\proSR\proSR-master>python test.py i-inputs --checkpoint models\proSR/proSR.pth --scale 2 -o outputs
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from prosr import Phase
  File "D:\proSR\proSR-master\lib\prosr\__init__.py", line 2, in <module>
    from . import metrics
  File "D:\proSR\proSR-master\lib\prosr\metrics.py", line 4, in <module>
    from skimage.measure import compare_psnr, compare_ssim
ImportError: cannot import name 'compare_psnr' from 'skimage.measure' (D:\proSR\lib\site-packages\skimage\measure\__init__.py)

**Comment by thejes-pixel** [comment]
I have the same exact problem. Did u manage to find a solution for this ? @johannhost 

> I was following a tutorial but its not working. Im new to anaconda and github, can someone tell me what I need to to in order to fix the code?
> 
> (D:\proSR) D:\proSR\proSR-master>python test.py i-inputs --checkpoint models\proSR/proSR.pth --scale 2 -o outputs
> Traceback (most recent call last):
> File "test.py", line 3, in
> from prosr import Phase
> File "D:\proSR\proSR-master\lib\prosr__init__.py", line 2, in
> from . import metrics
> File "D:\proSR\proSR-master\lib\prosr\metrics.py", line 4, in
> from skimage.measure import compare_psnr, compare_ssim
> ImportError: cannot import name 'compare_psnr' from 'skimage.measure' (D:\proSR\lib\site-packages\skimage\measure__init__.py)

**Comment by thejes-pixel** [comment]
I used measure.compare_psnr() and it worked for me.

**Comment by ajeema** [comment]
where?

**Comment by thejes-pixel** [comment]
You need to find the metrics.py file in the lib folder of the project:
Change this line :<from skimage.measure import compare_psnr, compare_ssim>
to <from skimage import   @@measure>
and then,
 psnr_val = measure.compare_psnr(im1_t, im2_t)
 ssim_val =measure.compare_ssim(.......)




> where?
