### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by rahidz** [fperazzi/proSR#9]
I've got 6 GB of GPU memory and the script constantly runs out of memory, are there any ways of reducing memory use?

Traceback (most recent call last):
  File "test.py", line 114, in <module>
    args.scale).cpu() + data['bicubic']
  File "/home/rahid/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rahid/proSR/lib/prosr/models/generators.py", line 124, in forward
    feats = getattr(self, 'pyramid_residual_%d' % s)(feats) + feats
  File "/home/rahid/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rahid/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/rahid/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rahid/proSR/lib/prosr/models/layers.py", line 179, in forward
    self).forward(x) + identity_x
  File "/home/rahid/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/rahid/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rahid/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/rahid/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rahid/proSR/lib/prosr/models/layers.py", line 150, in forward
    return torch.cat([x, new_features], 1)
RuntimeError: CUDA error: out of memory

**Comment by fperazzi** [comment]
Divide the image into four (slightly overlapping) quadrants, process them independently and recompose into the final SR image.

**Comment by rahidz** [comment]
Don't know why I didn't think of that, works perfectly! Thanks!

**Comment by ProGamerGov** [comment]
What image size where you able to achieve with a 6GB GPU and no tiling?

**Comment by stephanedebove** [comment]
> Don't know why I didn't think of that, works perfectly! Thanks!

@rahidz if you implemented that do you mind sharing your code for splitting the image and recomposing it at the end?

**Comment by fperazzi** [comment]
@ProGamerGov @stephanedebove @rahidz. I added code to split/recompose the image into chunks in `test.py`. You can use `--max-dimension` and `--padding` to set the size of the chunks.

**Comment by GabrielGuez** [comment]
> @ProGamerGov @stephanedebove @rahidz. I added code to split/recompose the image into chunks in `test.py`. You can use `--max-dimension` and `--padding` to set the size of the chunks.

Hi, I'm having the same issue but during training. 
Could I be able to use the features --max-dimension and --padding that you added in test.py, but in train.py ?

Sorry if it's a stupid question, I'm pretty new to this.

Thank you for your work and have a great day.
